worker_processes auto;
error_log stderr notice;
#error_log /var/log/nginx_error.log notice;

events {
    worker_connections 1024;
}

http {
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    access_log off;
    #access_log /var/log/nginx_access.log;

    proxy_cache_path /dev/shm/nginx_cache_s3 levels=1:2 use_temp_path=off keys_zone=cache_s3:100m inactive=24h max_size=16g;
    proxy_temp_path /dev/shm/nginx_proxy;

    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";

    server {
        listen 80 backlog=2048;

        location /tiles {
            content_by_lua_file /usr/local/openresty/nginx/lua/handle_tiles.lua;

            add_header Access-Control-Allow-Origin "*"; # TODO
        }

        location ~ /s3_proxy/(.*) {
            internal;

            resolver 127.0.0.11; # docker-compose internal dns server
            set $s3_host storage.yandexcloud.net;

            proxy_pass http://$s3_host/load2-bucket/$1;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $s3_host;
            proxy_set_header Range $http_range;

            proxy_cache cache_s3;
            proxy_cache_key "v0|$1|$http_range";
            proxy_cache_valid 206 24h;
            proxy_cache_valid 404 5s;
            proxy_cache_methods GET;
            proxy_cache_lock on;

            proxy_ignore_headers Cache-Control Expires Set-Cookie Vary;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}
