// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Location } from '../fbs/location';


export class DenseLocations {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DenseLocations {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDenseLocations(bb:flatbuffers.ByteBuffer, obj?:DenseLocations):DenseLocations {
  return (obj || new DenseLocations()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDenseLocations(bb:flatbuffers.ByteBuffer, obj?:DenseLocations):DenseLocations {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DenseLocations()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

locations(index: number, obj?:Location):Location|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Location()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

locationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDenseLocations(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLocations(builder:flatbuffers.Builder, locationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, locationsOffset, 0);
}

static startLocationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endDenseLocations(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDenseLocations(builder:flatbuffers.Builder, locationsOffset:flatbuffers.Offset):flatbuffers.Offset {
  DenseLocations.startDenseLocations(builder);
  DenseLocations.addLocations(builder, locationsOffset);
  return DenseLocations.endDenseLocations(builder);
}
}
