// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class FileHeader {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FileHeader {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

signature():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

version():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

dataOffset():bigint {
  return this.bb!.readUint64(this.bb_pos + 16);
}

dataSize():bigint {
  return this.bb!.readUint64(this.bb_pos + 24);
}

indexOffset():bigint {
  return this.bb!.readUint64(this.bb_pos + 32);
}

indexSize():bigint {
  return this.bb!.readUint64(this.bb_pos + 40);
}

metadataOffset():bigint {
  return this.bb!.readUint64(this.bb_pos + 48);
}

metadataSize():bigint {
  return this.bb!.readUint64(this.bb_pos + 56);
}

extendedOffset():bigint {
  return this.bb!.readUint64(this.bb_pos + 64);
}

extendedSize():bigint {
  return this.bb!.readUint64(this.bb_pos + 72);
}

reserved1():bigint {
  return this.bb!.readUint64(this.bb_pos + 80);
}

reserved2():bigint {
  return this.bb!.readUint64(this.bb_pos + 88);
}

static sizeOf():number {
  return 96;
}

static createFileHeader(builder:flatbuffers.Builder, signature: bigint, version: bigint, data_offset: bigint, data_size: bigint, index_offset: bigint, index_size: bigint, metadata_offset: bigint, metadata_size: bigint, extended_offset: bigint, extended_size: bigint, reserved1: bigint, reserved2: bigint):flatbuffers.Offset {
  builder.prep(8, 96);
  builder.writeInt64(BigInt(reserved2 ?? 0));
  builder.writeInt64(BigInt(reserved1 ?? 0));
  builder.writeInt64(BigInt(extended_size ?? 0));
  builder.writeInt64(BigInt(extended_offset ?? 0));
  builder.writeInt64(BigInt(metadata_size ?? 0));
  builder.writeInt64(BigInt(metadata_offset ?? 0));
  builder.writeInt64(BigInt(index_size ?? 0));
  builder.writeInt64(BigInt(index_offset ?? 0));
  builder.writeInt64(BigInt(data_size ?? 0));
  builder.writeInt64(BigInt(data_offset ?? 0));
  builder.writeInt64(BigInt(version ?? 0));
  builder.writeInt64(BigInt(signature ?? 0));
  return builder.offset();
}

}
