// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FileHeader } from '../fbs/file-header';
import { IndexHeader } from '../fbs/index-header';


export class Header {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Header {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

fileHeader(obj?:FileHeader):FileHeader|null {
  return (obj || new FileHeader()).__init(this.bb_pos, this.bb!);
}

indexHeader(obj?:IndexHeader):IndexHeader|null {
  return (obj || new IndexHeader()).__init(this.bb_pos + 96, this.bb!);
}

static sizeOf():number {
  return 192;
}

static createHeader(builder:flatbuffers.Builder, file_header_signature: bigint, file_header_version: bigint, file_header_data_offset: bigint, file_header_data_size: bigint, file_header_index_offset: bigint, file_header_index_size: bigint, file_header_metadata_offset: bigint, file_header_metadata_size: bigint, file_header_extended_offset: bigint, file_header_extended_size: bigint, file_header_reserved1: bigint, file_header_reserved2: bigint, index_header_magic: bigint, index_header_format: bigint, index_header_max_zoom: bigint, index_header_block_levels_mask: bigint, index_header_root_offset: bigint, index_header_root_size: bigint, index_header_reserved1: bigint, index_header_reserved2: bigint, index_header_reserved3: bigint, index_header_reserved4: bigint, index_header_reserved5: bigint, index_header_reserved6: bigint):flatbuffers.Offset {
  builder.prep(8, 192);
  builder.prep(8, 96);
  builder.writeInt64(BigInt(index_header_reserved6 ?? 0));
  builder.writeInt64(BigInt(index_header_reserved5 ?? 0));
  builder.writeInt64(BigInt(index_header_reserved4 ?? 0));
  builder.writeInt64(BigInt(index_header_reserved3 ?? 0));
  builder.writeInt64(BigInt(index_header_reserved2 ?? 0));
  builder.writeInt64(BigInt(index_header_reserved1 ?? 0));
  builder.writeInt64(BigInt(index_header_root_size ?? 0));
  builder.writeInt64(BigInt(index_header_root_offset ?? 0));
  builder.writeInt64(BigInt(index_header_block_levels_mask ?? 0));
  builder.writeInt64(BigInt(index_header_max_zoom ?? 0));
  builder.writeInt64(BigInt(index_header_format ?? 0));
  builder.writeInt64(BigInt(index_header_magic ?? 0));
  builder.prep(8, 96);
  builder.writeInt64(BigInt(file_header_reserved2 ?? 0));
  builder.writeInt64(BigInt(file_header_reserved1 ?? 0));
  builder.writeInt64(BigInt(file_header_extended_size ?? 0));
  builder.writeInt64(BigInt(file_header_extended_offset ?? 0));
  builder.writeInt64(BigInt(file_header_metadata_size ?? 0));
  builder.writeInt64(BigInt(file_header_metadata_offset ?? 0));
  builder.writeInt64(BigInt(file_header_index_size ?? 0));
  builder.writeInt64(BigInt(file_header_index_offset ?? 0));
  builder.writeInt64(BigInt(file_header_data_size ?? 0));
  builder.writeInt64(BigInt(file_header_data_offset ?? 0));
  builder.writeInt64(BigInt(file_header_version ?? 0));
  builder.writeInt64(BigInt(file_header_signature ?? 0));
  return builder.offset();
}

}
