// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum IndexFormat {
  Invalid = '0',
  BasicPlain = '1',
  Plain = '2',
  Sparse = '3'
}
