// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class IndexHeader {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IndexHeader {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

magic():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

format():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

maxZoom():bigint {
  return this.bb!.readUint64(this.bb_pos + 16);
}

blockLevelsMask():bigint {
  return this.bb!.readUint64(this.bb_pos + 24);
}

rootOffset():bigint {
  return this.bb!.readUint64(this.bb_pos + 32);
}

rootSize():bigint {
  return this.bb!.readUint64(this.bb_pos + 40);
}

reserved1():bigint {
  return this.bb!.readUint64(this.bb_pos + 48);
}

reserved2():bigint {
  return this.bb!.readUint64(this.bb_pos + 56);
}

reserved3():bigint {
  return this.bb!.readUint64(this.bb_pos + 64);
}

reserved4():bigint {
  return this.bb!.readUint64(this.bb_pos + 72);
}

reserved5():bigint {
  return this.bb!.readUint64(this.bb_pos + 80);
}

reserved6():bigint {
  return this.bb!.readUint64(this.bb_pos + 88);
}

static sizeOf():number {
  return 96;
}

static createIndexHeader(builder:flatbuffers.Builder, magic: bigint, format: bigint, max_zoom: bigint, block_levels_mask: bigint, root_offset: bigint, root_size: bigint, reserved1: bigint, reserved2: bigint, reserved3: bigint, reserved4: bigint, reserved5: bigint, reserved6: bigint):flatbuffers.Offset {
  builder.prep(8, 96);
  builder.writeInt64(BigInt(reserved6 ?? 0));
  builder.writeInt64(BigInt(reserved5 ?? 0));
  builder.writeInt64(BigInt(reserved4 ?? 0));
  builder.writeInt64(BigInt(reserved3 ?? 0));
  builder.writeInt64(BigInt(reserved2 ?? 0));
  builder.writeInt64(BigInt(reserved1 ?? 0));
  builder.writeInt64(BigInt(root_size ?? 0));
  builder.writeInt64(BigInt(root_offset ?? 0));
  builder.writeInt64(BigInt(block_levels_mask ?? 0));
  builder.writeInt64(BigInt(max_zoom ?? 0));
  builder.writeInt64(BigInt(format ?? 0));
  builder.writeInt64(BigInt(magic ?? 0));
  return builder.offset();
}

}
