// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LinkItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LinkItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

tileCode():number {
  return this.bb!.readUint32(this.bb_pos);
}

linkCode():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createLinkItem(builder:flatbuffers.Builder, tile_code: number, link_code: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(link_code);
  builder.writeInt32(tile_code);
  return builder.offset();
}

}
