// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Location {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Location {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

v0():number {
  return this.bb!.readUint32(this.bb_pos);
}

v1():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createLocation(builder:flatbuffers.Builder, v0: number, v1: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(v1);
  builder.writeInt32(v0);
  return builder.offset();
}

}
