// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Location } from '../fbs/location';


export class LocationItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LocationItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

tileCode():number {
  return this.bb!.readUint32(this.bb_pos);
}

location(obj?:Location):Location|null {
  return (obj || new Location()).__init(this.bb_pos + 4, this.bb!);
}

static sizeOf():number {
  return 12;
}

static createLocationItem(builder:flatbuffers.Builder, tile_code: number, location_v0: number, location_v1: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.prep(4, 8);
  builder.writeInt32(location_v1);
  builder.writeInt32(location_v0);
  builder.writeInt32(tile_code);
  return builder.offset();
}

}
