// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class ResponseParams {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseParams {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseParams(bb:flatbuffers.ByteBuffer, obj?:ResponseParams):ResponseParams {
  return (obj || new ResponseParams()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseParams(bb:flatbuffers.ByteBuffer, obj?:ResponseParams):ResponseParams {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseParams()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

contentType():string|null
contentType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentEncoding():string|null
contentEncoding(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentEncoding(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startResponseParams(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addContentType(builder:flatbuffers.Builder, contentTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, contentTypeOffset, 0);
}

static addContentEncoding(builder:flatbuffers.Builder, contentEncodingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentEncodingOffset, 0);
}

static endResponseParams(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishResponseParamsBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedResponseParamsBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createResponseParams(builder:flatbuffers.Builder, contentTypeOffset:flatbuffers.Offset, contentEncodingOffset:flatbuffers.Offset):flatbuffers.Offset {
  ResponseParams.startResponseParams(builder);
  ResponseParams.addContentType(builder, contentTypeOffset);
  ResponseParams.addContentEncoding(builder, contentEncodingOffset);
  return ResponseParams.endResponseParams(builder);
}
}
