// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlockType } from '../fbs/block-type';
import { DenseLocations } from '../fbs/dense-locations';
import { SparseLocations } from '../fbs/sparse-locations';


export class SparseBlock {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SparseBlock {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSparseBlock(bb:flatbuffers.ByteBuffer, obj?:SparseBlock):SparseBlock {
  return (obj || new SparseBlock()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSparseBlock(bb:flatbuffers.ByteBuffer, obj?:SparseBlock):SparseBlock {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SparseBlock()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

blockType():BlockType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : BlockType.Invalid;
}

denseLocations(index: number, obj?:DenseLocations):DenseLocations|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new DenseLocations()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

denseLocationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

sparseLocations(index: number, obj?:SparseLocations):SparseLocations|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new SparseLocations()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

sparseLocationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSparseBlock(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addBlockType(builder:flatbuffers.Builder, blockType:BlockType) {
  builder.addFieldInt32(0, blockType, BlockType.Invalid);
}

static addDenseLocations(builder:flatbuffers.Builder, denseLocationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, denseLocationsOffset, 0);
}

static createDenseLocationsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDenseLocationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSparseLocations(builder:flatbuffers.Builder, sparseLocationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sparseLocationsOffset, 0);
}

static createSparseLocationsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSparseLocationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSparseBlock(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSparseBlockBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSparseBlockBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createSparseBlock(builder:flatbuffers.Builder, blockType:BlockType, denseLocationsOffset:flatbuffers.Offset, sparseLocationsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SparseBlock.startSparseBlock(builder);
  SparseBlock.addBlockType(builder, blockType);
  SparseBlock.addDenseLocations(builder, denseLocationsOffset);
  SparseBlock.addSparseLocations(builder, sparseLocationsOffset);
  return SparseBlock.endSparseBlock(builder);
}
}
