// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LinkItem } from '../fbs/link-item';
import { LocationItem } from '../fbs/location-item';


export class SparseLocations {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SparseLocations {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSparseLocations(bb:flatbuffers.ByteBuffer, obj?:SparseLocations):SparseLocations {
  return (obj || new SparseLocations()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSparseLocations(bb:flatbuffers.ByteBuffer, obj?:SparseLocations):SparseLocations {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SparseLocations()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:LocationItem):LocationItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new LocationItem()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 12, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

links(index: number, obj?:LinkItem):LinkItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LinkItem()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

linksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSparseLocations(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(12, numElems, 4);
}

static addLinks(builder:flatbuffers.Builder, linksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, linksOffset, 0);
}

static startLinksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endSparseLocations(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSparseLocations(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, linksOffset:flatbuffers.Offset):flatbuffers.Offset {
  SparseLocations.startSparseLocations(builder);
  SparseLocations.addTiles(builder, tilesOffset);
  SparseLocations.addLinks(builder, linksOffset);
  return SparseLocations.endSparseLocations(builder);
}
}
