worker_processes auto;
error_log stderr notice;

events {
    worker_connections 1024;
}

thread_pool tiles_aio_threadpool threads=128 max_queue=32768;

http {
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    access_log off;

    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";
    lua_worker_thread_vm_pool_size 128; # in case of "no available Lua vm" errors

    server {
        listen 80 backlog=2048;

        # gzip on;
        # gzip_types application/x-protobuf application/vnd.mapbox-vector-tile;
        # gunzip on;

        location ~ /tiles/\d+/\d+/\d+ {
            content_by_lua_file /usr/local/openresty/nginx/lua/handle_tiles.lua;

            add_header Access-Control-Allow-Origin "*"; # TODO
        }

        location / {
            return 404;
        }
    }
}
