--[[ webtiles.fbs.BlockType

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local BlockType = {
  Invalid = 0,
  Dense = 1,
  Sparse = 2,
}

return BlockType