--[[ webtiles.fbs.DenseLocations

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local __webtiles_fbs_Location = require('webtiles.fbs.Location')
local flatbuffers = require('flatbuffers')

local DenseLocations = {}
local mt = {}

function DenseLocations.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Locations(j)
  local o = self.view:Offset(4)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 8)
    local obj = __webtiles_fbs_Location.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:LocationsLength()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function DenseLocations.Start(builder)
  builder:StartObject(1)
end

function DenseLocations.AddLocations(builder, locations)
  builder:PrependUOffsetTRelativeSlot(0, locations, 0)
end

function DenseLocations.StartLocationsVector(builder, numElems)
  return builder:StartVector(8, numElems, 4)
end

function DenseLocations.End(builder)
  return builder:EndObject()
end

return DenseLocations