--[[ webtiles.fbs.FileHeader

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local flatbuffers = require('flatbuffers')

local FileHeader = {}
local mt = {}

function FileHeader.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Signature()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 0)
end

function mt:Version()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 8)
end

function mt:DataOffset()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 16)
end

function mt:DataSize()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 24)
end

function mt:IndexOffset()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 32)
end

function mt:IndexSize()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 40)
end

function mt:MetadataOffset()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 48)
end

function mt:MetadataSize()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 56)
end

function mt:ExtendedOffset()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 64)
end

function mt:ExtendedSize()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 72)
end

function mt:Reserved1()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 80)
end

function mt:Reserved2()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 88)
end

function FileHeader.CreateFileHeader(builder, signature, version, dataOffset, dataSize, indexOffset, indexSize, metadataOffset, metadataSize, extendedOffset, extendedSize, reserved1, reserved2)
  builder:Prep(8, 96)
  builder:PrependUint64(reserved2)
  builder:PrependUint64(reserved1)
  builder:PrependUint64(extendedSize)
  builder:PrependUint64(extendedOffset)
  builder:PrependUint64(metadataSize)
  builder:PrependUint64(metadataOffset)
  builder:PrependUint64(indexSize)
  builder:PrependUint64(indexOffset)
  builder:PrependUint64(dataSize)
  builder:PrependUint64(dataOffset)
  builder:PrependUint64(version)
  builder:PrependUint64(signature)
  return builder:Offset()
end

return FileHeader