--[[ webtiles.fbs.HeaderVersion

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local HeaderVersion = {
  Invalid = 0,
  V01 = 1,
  V02 = 2,
}

return HeaderVersion