--[[ webtiles.fbs.HeaderSize

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local HeaderSize = {
  Regular = 192,
  Extended = 512,
}

return HeaderSize