--[[ webtiles.fbs.Header

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Header = {}
local mt = {}

function Header.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:FileHeader(obj)
  obj:Init(self.view.bytes, self.view.pos + 0)
  return obj
end

function mt:IndexHeader(obj)
  obj:Init(self.view.bytes, self.view.pos + 96)
  return obj
end

function Header.CreateHeader(builder, fileHeader_signature, fileHeader_version, fileHeader_dataOffset, fileHeader_dataSize, fileHeader_indexOffset, fileHeader_indexSize, fileHeader_metadataOffset, fileHeader_metadataSize, fileHeader_extendedOffset, fileHeader_extendedSize, fileHeader_reserved1, fileHeader_reserved2, indexHeader_magic, indexHeader_format, indexHeader_maxZoom, indexHeader_blockLevelsMask, indexHeader_rootOffset, indexHeader_rootSize, indexHeader_reserved1, indexHeader_reserved2, indexHeader_reserved3, indexHeader_reserved4, indexHeader_reserved5, indexHeader_reserved6)
  builder:Prep(8, 192)
  builder:Prep(8, 96)
  builder:PrependUint64(indexHeader_reserved6)
  builder:PrependUint64(indexHeader_reserved5)
  builder:PrependUint64(indexHeader_reserved4)
  builder:PrependUint64(indexHeader_reserved3)
  builder:PrependUint64(indexHeader_reserved2)
  builder:PrependUint64(indexHeader_reserved1)
  builder:PrependUint64(indexHeader_rootSize)
  builder:PrependUint64(indexHeader_rootOffset)
  builder:PrependUint64(indexHeader_blockLevelsMask)
  builder:PrependUint64(indexHeader_maxZoom)
  builder:PrependUint64(indexHeader_format)
  builder:PrependUint64(indexHeader_magic)
  builder:Prep(8, 96)
  builder:PrependUint64(fileHeader_reserved2)
  builder:PrependUint64(fileHeader_reserved1)
  builder:PrependUint64(fileHeader_extendedSize)
  builder:PrependUint64(fileHeader_extendedOffset)
  builder:PrependUint64(fileHeader_metadataSize)
  builder:PrependUint64(fileHeader_metadataOffset)
  builder:PrependUint64(fileHeader_indexSize)
  builder:PrependUint64(fileHeader_indexOffset)
  builder:PrependUint64(fileHeader_dataSize)
  builder:PrependUint64(fileHeader_dataOffset)
  builder:PrependUint64(fileHeader_version)
  builder:PrependUint64(fileHeader_signature)
  return builder:Offset()
end

return Header