--[[ webtiles.fbs.HeaderSignature

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local HeaderSignature = {
  Invalid = 0,
  Value = 91557097722967,
}

return HeaderSignature