--[[ webtiles.fbs.IndexHeader

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local flatbuffers = require('flatbuffers')

local IndexHeader = {}
local mt = {}

function IndexHeader.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Magic()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 0)
end

function mt:Format()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 8)
end

function mt:MaxZoom()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 16)
end

function mt:BlockLevelsMask()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 24)
end

function mt:RootOffset()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 32)
end

function mt:RootSize()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 40)
end

function mt:Reserved1()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 48)
end

function mt:Reserved2()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 56)
end

function mt:Reserved3()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 64)
end

function mt:Reserved4()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 72)
end

function mt:Reserved5()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 80)
end

function mt:Reserved6()
  return self.view:Get(flatbuffers.N.Uint64, self.view.pos + 88)
end

function IndexHeader.CreateIndexHeader(builder, magic, format, maxZoom, blockLevelsMask, rootOffset, rootSize, reserved1, reserved2, reserved3, reserved4, reserved5, reserved6)
  builder:Prep(8, 96)
  builder:PrependUint64(reserved6)
  builder:PrependUint64(reserved5)
  builder:PrependUint64(reserved4)
  builder:PrependUint64(reserved3)
  builder:PrependUint64(reserved2)
  builder:PrependUint64(reserved1)
  builder:PrependUint64(rootSize)
  builder:PrependUint64(rootOffset)
  builder:PrependUint64(blockLevelsMask)
  builder:PrependUint64(maxZoom)
  builder:PrependUint64(format)
  builder:PrependUint64(magic)
  return builder:Offset()
end

return IndexHeader