--[[ webtiles.fbs.IndexMagic

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local IndexMagic = {
  Invalid = 0,
  Value = 1481200727,
}

return IndexMagic