--[[ webtiles.fbs.IndexFormat

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //header.fbs
  Rooting type : webtiles.fbs.FakeRoot (//header.fbs)

--]]

local IndexFormat = {
  Invalid = 0,
  BasicPlain = 1,
  Plain = 2,
  Sparse = 3,
}

return IndexFormat