--[[ webtiles.fbs.LinkItem

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local flatbuffers = require('flatbuffers')

local LinkItem = {}
local mt = {}

function LinkItem.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:TileCode()
  return self.view:Get(flatbuffers.N.Uint32, self.view.pos + 0)
end

function mt:LinkCode()
  return self.view:Get(flatbuffers.N.Uint32, self.view.pos + 4)
end

function LinkItem.CreateLinkItem(builder, tileCode, linkCode)
  builder:Prep(4, 8)
  builder:PrependUint32(linkCode)
  builder:PrependUint32(tileCode)
  return builder:Offset()
end

return LinkItem