--[[ webtiles.fbs.Location

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Location = {}
local mt = {}

function Location.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:V0()
  return self.view:Get(flatbuffers.N.Uint32, self.view.pos + 0)
end

function mt:V1()
  return self.view:Get(flatbuffers.N.Uint32, self.view.pos + 4)
end

function Location.CreateLocation(builder, v0, v1)
  builder:Prep(4, 8)
  builder:PrependUint32(v1)
  builder:PrependUint32(v0)
  return builder:Offset()
end

return Location