--[[ webtiles.fbs.LocationItem

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local flatbuffers = require('flatbuffers')

local LocationItem = {}
local mt = {}

function LocationItem.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:TileCode()
  return self.view:Get(flatbuffers.N.Uint32, self.view.pos + 0)
end

function mt:Location(obj)
  obj:Init(self.view.bytes, self.view.pos + 4)
  return obj
end

function LocationItem.CreateLocationItem(builder, tileCode, location_v0, location_v1)
  builder:Prep(4, 12)
  builder:Prep(4, 8)
  builder:PrependUint32(location_v1)
  builder:PrependUint32(location_v0)
  builder:PrependUint32(tileCode)
  return builder:Offset()
end

return LocationItem