--[[ webtiles.fbs.ResponseParams

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //response_params.fbs
  Rooting type : webtiles.fbs.ResponseParams (//response_params.fbs)

--]]

local flatbuffers = require('flatbuffers')

local ResponseParams = {}
local mt = {}

function ResponseParams.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function ResponseParams.GetRootAsResponseParams(buf, offset)
  if type(buf) == "string" then
    buf = flatbuffers.binaryArray.New(buf)
  end

  local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
  local o = ResponseParams.New()
  o:Init(buf, n + offset)
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:ContentType()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function mt:ContentEncoding()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function ResponseParams.Start(builder)
  builder:StartObject(2)
end

function ResponseParams.AddContentType(builder, contentType)
  builder:PrependUOffsetTRelativeSlot(0, contentType, 0)
end

function ResponseParams.AddContentEncoding(builder, contentEncoding)
  builder:PrependUOffsetTRelativeSlot(1, contentEncoding, 0)
end

function ResponseParams.End(builder)
  return builder:EndObject()
end

return ResponseParams