--[[ webtiles.fbs.SparseBlock

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local __webtiles_fbs_DenseLocations = require('webtiles.fbs.DenseLocations')
local __webtiles_fbs_SparseLocations = require('webtiles.fbs.SparseLocations')
local flatbuffers = require('flatbuffers')

local SparseBlock = {}
local mt = {}

function SparseBlock.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function SparseBlock.GetRootAsSparseBlock(buf, offset)
  if type(buf) == "string" then
    buf = flatbuffers.binaryArray.New(buf)
  end

  local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
  local o = SparseBlock.New()
  o:Init(buf, n + offset)
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:BlockType()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint32, self.view.pos + o)
  end
  return 0
end

function mt:DenseLocations(j)
  local o = self.view:Offset(6)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 4)
    x = self.view:Indirect(x)
    local obj = __webtiles_fbs_DenseLocations.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:DenseLocationsLength()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function mt:SparseLocations(j)
  local o = self.view:Offset(8)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 4)
    x = self.view:Indirect(x)
    local obj = __webtiles_fbs_SparseLocations.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:SparseLocationsLength()
  local o = self.view:Offset(8)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function SparseBlock.Start(builder)
  builder:StartObject(3)
end

function SparseBlock.AddBlockType(builder, blockType)
  builder:PrependUint32Slot(0, blockType, 0)
end

function SparseBlock.AddDenseLocations(builder, denseLocations)
  builder:PrependUOffsetTRelativeSlot(1, denseLocations, 0)
end

function SparseBlock.StartDenseLocationsVector(builder, numElems)
  return builder:StartVector(4, numElems, 4)
end

function SparseBlock.AddSparseLocations(builder, sparseLocations)
  builder:PrependUOffsetTRelativeSlot(2, sparseLocations, 0)
end

function SparseBlock.StartSparseLocationsVector(builder, numElems)
  return builder:StartVector(4, numElems, 4)
end

function SparseBlock.End(builder)
  return builder:EndObject()
end

return SparseBlock