--[[ webtiles.fbs.SparseLocations

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 25.2.10

  Declared by  : //sparse_block.fbs
  Rooting type : webtiles.fbs.SparseBlock (//sparse_block.fbs)

--]]

local __webtiles_fbs_LinkItem = require('webtiles.fbs.LinkItem')
local __webtiles_fbs_LocationItem = require('webtiles.fbs.LocationItem')
local flatbuffers = require('flatbuffers')

local SparseLocations = {}
local mt = {}

function SparseLocations.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Tiles(j)
  local o = self.view:Offset(4)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 12)
    local obj = __webtiles_fbs_LocationItem.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:TilesLength()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function mt:Links(j)
  local o = self.view:Offset(6)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 8)
    local obj = __webtiles_fbs_LinkItem.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:LinksLength()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function SparseLocations.Start(builder)
  builder:StartObject(2)
end

function SparseLocations.AddTiles(builder, tiles)
  builder:PrependUOffsetTRelativeSlot(0, tiles, 0)
end

function SparseLocations.StartTilesVector(builder, numElems)
  return builder:StartVector(12, numElems, 4)
end

function SparseLocations.AddLinks(builder, links)
  builder:PrependUOffsetTRelativeSlot(1, links, 0)
end

function SparseLocations.StartLinksVector(builder, numElems)
  return builder:StartVector(8, numElems, 4)
end

function SparseLocations.End(builder)
  return builder:EndObject()
end

return SparseLocations